site:
  name: EFCARE
  site: 'https://efcare.vn'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: 'EFCARE — Quản lý sức khỏe gia đình từ nhà đến bệnh viện'
    template: '%s — EFCARE'
  description: 'EFCARE là hệ sinh thái chăm sóc sức khỏe gia đình đa thế hệ, kết nối công nghệ, y tế và cộng đồng trong một nền tảng minh bạch, nhân văn và bền vững.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: EFCARE
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@efcare_vn'
    site: '@efcare_vn'
    cardType: summary_large_image

i18n:
  language: vi
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/bai-viet/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'bai-viet' # Blog main path
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'danh-muc' # Category main path
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'the' # Tag main path
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
